### ISSUE TITLE
Provide README

### ISSUE THREAD

**Issue by fokusferit** [wholesale-design-system/styleguide#5]
We should create a README also for our styleguide project. Maybe it doesn't has to be as long as the components README but I think the following points should be written down:

- Motivation (Why?) 
- Technical Concepts (A short explanation how the styleguide works, a diagram showing all dependencies and how styleguide works.)
- Getting started (How to test changes locally ?, how to contribute)
- Contributing
- License

**Comment by schluchter** [comment]
Great idea. I can contribute a first draft of the Why.

**Comment by fokusferit** [comment]
@schluchter see https://github.com/wholesale-design-system/components#motivation as a basic motivation :D maybe you have something more general.

**Comment by fokusferit** [comment]
@schluchter still up for this challenge ?

**Comment by schluchter** [comment]
Definitely. Adrian has some first thoughts on it that I'll go over next
week.

**Comment by mroderick** [comment]
I think this can be closed
